### PR TITLE
Update microG to v0.2.27.223616

### PR DESCRIPTION
**Pull request by ac130kz**
https://github.com/microg/GmsCore/releases/tag/v0.2.27.223616

### CODE REVIEW

**Comment by nift4** [comment]
is boot tested?

**Comment by ac130kz** [comment]
I've installed it directly by downloading and installing the apk, so far so good.
Screenshot_20230115-224342_microG Services Core
Screenshot_20230115-224346_microG Services Core

**Comment by nift4** [comment]
Sadly, that makes a big difference, therefore one needs to manually patch the module with the new microG version to test.

**Comment by leso-kn** [comment]
Tested @ac130kz's on Android 10 (Oneplus 5 `cheeseburger`), microg seems to be working fine and phone is booting.

**Note** As shown in the second screenshot, the apk signature seems to not match the one on the microg F-Droid repository anymore. Is this expected?

In any case this is not related to the new version, the signature mismatch had already been present on the latest released version of nift4/microg_installer_revived.

**Comment by ac130kz** [comment]
@leso-kn MicroG use a different signature for their own website, I'm also not sure which one to use

**Comment by leso-kn** [comment]
Hm, indeed. Looking at their website, it seems like the signature used by their F-Droid repository is recommended:

> The best method to download and update components of the microG Project is to use our F-Droid repositories. It currently provides stable and nightly updates for GmsCore as well as releases of GsfProxy and FakeStore. [[1]](https://microg.org/download.html)

and

> This is a repository of microG apps to be used with F-Droid. Applications in this repository are **signed official binaries** built by the microG Team from the corresponding source code. [[1]](https://microg.org/download.html)

What do you think @nift4?

**Comment by nift4** [comment]
I use APKs downloaded from their GitHub 🤷

**Comment by nift4** [comment]
3.2 released (with APK downloaded from GitHub to avoid misunderstandings or confusing)

**Pull request closed without merging**
